### ISSUE TITLE
Podfile errors

### ISSUE THREAD

**Issue by santanu4ver** [Weebly/TableSchemer#3]
Hi,

When downloaded sources I'm getting compiler errors as following. Please, suggest hot to overcome.

Run custom shell script 'Check Pods Manifest.lock'
------------------------------------------------------------
------------------------------------------------------------
diff: /../Podfile.lock: No such file or directory
diff: Manifest.lock: No such file or directory error: 
The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

Thank you!

Regards,

Santanu

**Comment by ketzusaka** [comment]
Hi Santanu,

After cloning the repository you need to run "pod install" in the directory. You'll need to install Cocoa Pods for that command to work.

I'll update the documentation about the sample project so thats clear.

Lemme know if that helps!
James

**Comment by santanu4ver** [comment]
Hi James,

Thanks. I've installed Cocoapods and after running 'pod install' previous errors have gone but I reported with a new error:

error: linker command failed with exit code 1 (use -v to see invocation)
Library not found for -IPods-TableSchemerTests-OCMock

Running 'pod install' didn't reported any command error, though. 

Sorry my minimal knowledge about this Cocapods - I'm a new comer to iOS/Swift.

Thanks! 

Regards,

Santanu

**Comment by ketzusaka** [comment]
No problem!

After you run pod install, be sure to open the workspace file (.xcworkspace) and not the project file, otherwise the project will not know how to find the pod dependencies.

**Comment by santanu4ver** [comment]
Great! Thanks!

**Comment by ketzusaka** [comment]
I've updated the README with more instructions on getting it to run. Thanks for letting me know about the difficulties!
