### ISSUE TITLE
scheme configurationHandler 

### ISSUE THREAD

**Issue by HUGEwindow** [Weebly/TableSchemer#6]
When using an accordion scheme: 

If opening an accordion places a scheme above it offscreen then it will format the offscreen scheme with the accordion cell format( not  the one in it's own configuration).  

Is there a quick way to fix this? 

Thanks.

**Comment by ketzusaka** [comment]
Do you have optimizations on by any chance? Swift is still quite bad at optimizing code, and has picked incorrect blocks to execute. 

Digging in some as well.

**Comment by ketzusaka** [comment]
Also, if its going offscreen, UITableView shouldn't be attempting to reconfigure it.

**Comment by HUGEwindow** [comment]
I turned optimizations to fast, I created a temp workaround, but I want to fix.  When UITableView goes offscreen it unloads cells.  Upon return it adds the attributes of ell your interacting with. My work around is to overwrite the attributes on the offscreen cells. 

Thanks for your response & work.

**Comment by ketzusaka** [comment]
Your UITableView is going offscreen, or cells in it?

You said the offscreen cell gets formatted by the accordion cell format, and not its own; when does this happen? When you scroll up and it needs to get reconfigured?

No problem! :)

**Comment by HUGEwindow** [comment]
When you select on accordion cell, it expands (pushing other sections offscreen) & then you select another cell to close (bringing other sections back & reloading them).

**Comment by HUGEwindow** [comment]
Do you know an easy way to keep original cell that activates the accordion(displaying the contents beneath)?

**Comment by HUGEwindow** [comment]
I had not been  using a unique identifier, my apologies. Not familiar with tables.

**Comment by ketzusaka** [comment]
Not a problem! As for changing the behavior of the accordion scheme, you'll have to create a custom one. Its super easy though and theres a post in the Wiki about how to do it. :)
